python3 txt_to_places.py ../data/Kaohsiung.txt --region "Kaohsiung, Taiwan" --trip "Kaohsiung"
python3 txt_to_places.py ../data/Chiayi.txt --region "Chiayi City, Taiwan" --trip "Chiayi"
python3 txt_to_places.py "../data/Jiufen and Shifen.txt" --region "New Taipei, Taiwan" --trip "Jiufen and Shifen"
python3 txt_to_places.py "../data/Sun Moon Lake.txt" --region "Nantou County, Taiwan" --trip "Sun Moon Lake"
python3 txt_to_places.py ../data/Taichung.txt --region "Taichung, Taiwan" --trip "Taichung"
python3 txt_to_places.py ../data/Alishan.txt --region "Alishan, Chiayi County, Taiwan" --trip "Alishan"
python3 txt_to_places.py ../data/Guangzhou.txt --region "Guangzhou, China" --trip "Guangzhou"
python3 txt_to_places.py "../data/Hong Kong.txt" --region "Hong Kong" --trip "Hong Kong"
python3 txt_to_places.py ../data/Taipei.txt --region "Taipei, Taiwan" --trip "Taipei"